### ISSUE TITLE
Issue with queue "not being handled" and moved during handling

### ISSUE THREAD

**Issue by special-K-Ken** [Shuttle/Shuttle.Esb#19]
Hi - I've got a weird scenario as follows.

A message is dropped onto a private transactional MSMQ queue (permissions opened up to everyone for purposes of test). This part works fine

A servicebus host class library hosted within Shuttle then reads the appropriate workQueueUri.
The servicebus host is using SimpleInjector as a container.  I've created a message handler factory 

`public class MessHandlerFactory : MessageHandlerFactory `

using the Unity example for inspiration.  Within the factory, it is detecting the containered' handler class.
All fine so far. 
The shuttle exe spins up, and all seems to be well.
A message is dropped into the worker queue. Shuttle picks this up.  
The factory works out this message type and spins up a handler.
The message handler is invoked - and can be debugged and the context/message appears as expected.

Now it gets interesting / weird
Then during the process of this message being handled - the underlying message is moved from the current queue to an error queue with a message "No handler has been registered for message type..." (even though we're processing said message in the debugger at this moment in time.
The handler completes its logic, and the factory goes through its releasehandler block.  At the very end of this bit - an exception is raised "Message requested was not found in the queue specified"

After this, the system then falls apart.

So in summary.
Handler picks up message. Shuttle moves it to an error queue as "no handler".  Handler cannot fully complete message as it's been moved to error queue.

I've tried this with both shuttle esb v6 and v7.0.4 add have the same issue in both.

The servicehost looks partly like
```
public class ServiceHost : IHost, IDisposable
    {
        private Container _container;
        private IServiceBus _serviceBus;
        private static readonly Type MessageHandlerType = typeof(IMessageHandler<>);

        public void Start()
        {
            Log.Assign(new Log4NetLog(LogManager.GetLogger(typeof(ServiceHost))));

            _container = new Container();

            // Ioc registrations
            RegisterComponents(_container);

            var messageFact = new MessHandlerFactory(_container);
            //var messageFact = new SimpleMessageHandlerFactory(_container);

            _serviceBus = Shuttle.Esb.ServiceBus.Create(c =>
            {
                c.MessageHandlerFactory(messageFact);
            });

            _serviceBus.Start();
        }
```

The message handler factory looks like
```
public class MessHandlerFactory : MessageHandlerFactory
    {
        private static readonly Type MessageHandlerType = typeof(IMessageHandler<>);
        private readonly Dictionary<Type, Type> _messageHandlerTypes = new Dictionary<Type, Type>();

        private static Container _container;


        public MessHandlerFactory(Container container)
        {
            _container = container;

            var types = _container.GetCurrentRegistrations()
                .Where(x =>
                    x.ServiceType.IsGenericType &&
                    x.ServiceType.GetGenericTypeDefinition() == MessageHandlerType).ToList();

            foreach (InstanceProducer instanceProducer in types)
            {
                Type messageType = instanceProducer.ServiceType.GetGenericArguments().FirstOrDefault();
                AddMessageTypeHandler(messageType, instanceProducer.ServiceType);
            }
        }

        private void AddMessageHandlerType(Type messageHandlerType)
        {
            foreach (Type type2 in messageHandlerType.GetInterfaces())
            {
                if (type2.IsGenericType && !(type2.GetGenericTypeDefinition() != MessageHandlerType))
                {
                    AddMessageTypeHandler(type2.GetGenericArguments()[0], messageHandlerType);
                }
            }
        }

        private void AddMessageTypeHandler(Type messageType, Type messageHandlerType)
        {
            if (_messageHandlerTypes.ContainsKey(messageType))
            {
                return;
            }
            _messageHandlerTypes.Add(messageType, messageHandlerType);
        }


        public override object CreateHandler(object message)
        {
            var output = _container.GetInstance(MessageHandlerType.MakeGenericType(message.GetType()));
            return output;
        }

        public override IMessageHandlerFactory RegisterHandlers(Assembly assembly)
        {
            foreach (Type type in new ReflectionService().GetTypes(MessageHandlerType, assembly))
            {
                if (type.GetConstructor(Type.EmptyTypes) != null)
                {
                    RegisterHandler(type);
                }
            }
            return this;
        }

        public override IMessageHandlerFactory RegisterHandler(Type type)
        {
            AddMessageHandlerType(type);
            return this;
        }

        public override IEnumerable<Type> MessageTypesHandled => _messageHandlerTypes.Keys;
    }
```

**Comment by eben-roux** [comment]
Apologies for getting back to you so late...

Not quite sure why this is happening.  Does it work OK if you do *not* debug?

Else you are welcome to send me a simplified sample and I'll have a look: me@ebenroux.co.za

**Comment by special-K-Ken** [comment]
Hi Eben. Thanks for the response.  For info - I've identified the issue.  In a nutshell, I was effectively creating 2x IServiceBus instances.  One was identifying the container and handling the queued message, then the second instance would come along (which wasn't connected to the DI container) and thus unable to handle the message. This secondary instance would then cause the message to be moved to the error queue.  So when the first instance was completing it's work and trying to release the handler it would then error due to the message having been moved by the other instance.

If you need any more info then please let me know! :)

**Comment by eben-roux** [comment]
Good to hear...

Thanks for the feedback.
