### ISSUE TITLE
v8 is ready for production

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Esb#20]
I have been using shuttle v7.x in production for some time and like to know if the v8 is ready for production or if it is in beta

**Comment by eben-roux** [comment]
The inner working of Shuttle.Esb haven't changed.  Only the wiring has changed.  I would recommend that you run through your normal testing cycle but other that that I cannot see why v8 would not be ready for production.  All my tests pass and all the samples function as expected.

**Comment by eben-roux** [comment]
Please let me know if you run into any specific issues with v8 should you decide to go ahead and upgrade :)
