### ISSUE TITLE
How can I defer a message inside a handler

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Esb#25]
Hi,

What is the best to defer a message inside the [ProcessMessage] method of a handler. I need to resend the message or just set the [IgnoreTillDate]?

**Comment by eben-roux** [comment]
If you simply want to defer the same message I guess you could send it locally again.  The handler would return as successful and the current message would be acknowledged:

``` c#
context.Send(context.Message, c => c.Local().Defer(DateTime.Now.AddMinutes(5)));
```
