### ISSUE TITLE
transactionScope is not recognized in v8

### ISSUE THREAD

**Issue by nohros** [Shuttle/Shuttle.Esb#28]
When starting a process that has ```transactionScope``` tag the process fails with the given error:

**Element 'transactionScope' não reconhecido.(J:\... line 27)**

The config file is similar to the following:

```xml
<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="serviceBus" type="Shuttle.Esb.ServiceBusSection, Shuttle.Esb"/>
    <section name="subscription" type="Shuttle.Esb.Sql.Subscription.SubscriptionSection, Shuttle.Esb.Sql.Subscription"/>
  </configSections>

  <connectionStrings>
    <add providerName="System.Data.SqlClient"
         name="shuttle"
         connectionString="*******"/>
  </connectionStrings>

  <serviceBus>
    <inbox
      workQueueUri="sql://shuttle/joins_correlator"
      errorQueueUri="sql://shuttle/error"
      deferredQueueUri="sql://shuttle/joins_correlator_deferred"
      durationToIgnoreOnFailure="10s,30s,1m"/>

    <transactionScope
      enabled="false"
      isolationLevel="ReadCommitted"
      timeoutSeconds="30" />

    <messageRoutes>
      <messageRoute uri="sql://shuttle/joins_correlator">
        <add specification="StartsWith" value="****"/>
      </messageRoute>
    </messageRoutes>
  </serviceBus>
```

**Comment by eben-roux** [comment]
Apologies for only responding now.  I seem to have failed to mention this in the upgrade guide and it also isn't documented properly.

The transaction scope configuration has been moved to the `Shuttle.Core.Infrastructure` package and has its own configuration section.  You can view [sample here](https://github.com/Shuttle/Shuttle.Core.Infrastructure/blob/master/Shuttle.Core.Infrastructure.Tests/TransactionScopeSection/files/TransactionScope.config).

I have opened these two issue to fix the docs:

- https://github.com/Shuttle/Shuttle.Core.Infrastructure/issues/6
- https://github.com/Shuttle/shuttle-esb/issues/60
