### ISSUE TITLE
IResuabillity interface not honoured in V8

### ISSUE THREAD

**Issue by lawrences-racti** [Shuttle/Shuttle.Esb#30]
We have noticed with the refactor to V8 the MessageHandlerFactory.ReleaseHandler is no longer implemented. This code used to  check the IResuability interface value if implemented and not re-use the handler. The replacement DefaultMessageHandlerInvoker caches the handlers per thread and seems to always resuse the handler if the threadId is the same.

**Comment by eben-roux** [comment]
Hello,

This issue should be resolved in the following release:

- https://github.com/Shuttle/Shuttle.Esb/releases/tag/v8.0.9

Regards,
Eben

**Comment by eben-roux** [comment]
Closing this for now.  If you still experience an issue please re-open.
