### ISSUE TITLE
Rebuild for .Net Standard

### ISSUE THREAD

**Issue by lawrences-racti** [Shuttle/Shuttle.Esb#32]
Is there any chance you would be able to get Shuttle to multi-target .Net Standard as well as the .Net framework where applicable? This seems to be the way nuget packages are going these days. We are still only targeting Windows but mixing .net framework and .net core/standard.

**Comment by eben-roux** [comment]
This is in the pipeline.  Unfortunately I have not had time to get around to it and I've been waiting to see what happens in the core space.  It *does* appear to be picking up steam.

I will need to move everything over to VS2017 which probably isn't a big deal but needs to be done none-the-less :)

I do think some of the bits will need to be refactored though when there are no .Net Core equivalents such as the configuration management.

**Comment by lawrences-racti** [comment]
If the projects that contain the Interfaces (Shuttle.Esb I think) could be done this would help. This way we could have the IMessageHandler<Message> code in the .Net Standard class library or a .net core class library and the configuration in a framework library.

**Comment by eben-roux** [comment]
Unfortunately it is probably a bit more involved.  The dependency injection interfaces live in Shuttle.Core.Infrastructure and then all the implementations of that and the Shuttle.Esb interfaces would need *at least* one implementation, e.g. RabbitMQ and the Shuttle.Esb.Sql* bits.

Anyway, I've started so I'll see how far I get.  I am on leave till 8 Jan 2018 so I have a bit of time to focus on this.

**Comment by eben-roux** [comment]
I released v10.0.0 today (13 Feb 2018) that supports .Net 4.6+ as well as .Net Core/Standard 2.0+.

If you do end up using it please log any issues as we deal with any teething problems :)
