### ISSUE TITLE
ISubscriptionManager defaulting to NullSubscriptionManager imp

### ISSUE THREAD

**Issue by WoozChucky** [Shuttle/Shuttle.Esb#37]
Hello, i'm trying to follow the GitHub sample for the Shuttle.PublishSubscribe example.

Everything works as intended except the [Subscriber](https://github.com/Shuttle/Shuttle.Esb.Samples/blob/master/Shuttle.PublishSubscribe/Shuttle.PublishSubscribe.Subscriber/Host.cs#L24) part.

I'm using RabbitMQ 3.7.7 and the message is published successfully from the client app to the server app. Also, the `MemberRegisteredEvent` is fired.

I'm using Autofac for IoC.

The error occurs in the Subscriber app whenever I try to fetch the `ISubscriptionManager` to _Subscribe_ to the `MemberRegisteredEvent`.

Here is my Host.cs code:

```csharp
public class Host : IServiceHost
    {

        IServiceBus _bus;

        public void Start()
        {
            var containerBuilder = new ContainerBuilder();

            var registry = new AutofacComponentRegistry(containerBuilder);

            ServiceBus.Register(registry);

            var resolver = new AutofacComponentResolver(containerBuilder.Build());

            resolver.Resolve<ISubscriptionManager>().Subscribe<MemberRegisteredEvent>();
            //Line above throws NotImplementedException("NullSubscriptionManager");

            _bus = ServiceBus.Create(resolver).Start();
        }

        public void Stop()
        {
            _bus.Dispose();
        }
    }
```

Am I missing something ?

**Comment by eben-roux** [comment]
This seems to indicate that the subscription manager implementation from `Shuttle.Esb.Sql.Subscription` has not been registered.

Perhaps check that the [package](https://www.nuget.org/packages?q=Shuttle.Esb.Sql.Subscription) is being referenced in your "Subscriber" application.

**Comment by eben-roux** [comment]
Apologies, somehow I thought you were running the samples but I see that you are following the guides (by the looks of it).

The default behaviour is to use the `NullSubscriptionManager` if not `ISubscriptionManager` is registered before starting the bus.

You could simply reference add the `Shuttle.Esb.Sql.Subscription` package and it will use the [bootstrapping](http://shuttle.github.io/shuttle-core/shuttle-core-container/#Bootstrapping) mechanism to register the `Shuttle.Esb.Sql.Subscription.SubscriptionManager` type.

It is also possible to register any other implementaion of the `ISubscriptionManager` interface before calling the `ServiceBus.Register(registry);` method.

**Comment by WoozChucky** [comment]
Thanks for the information @eben-roux !
I managed to get it working with the `Shuttle.Esb.Sql.Subscription`package.

Is there any other implementation of `ISubscriptionManager`that uses for example InMemory subscription rather than SQL ? Or it is easy enough to implement it myself ?

**Comment by eben-roux** [comment]
The `Shuttle.Esb.Sql.Subscription` package include a **Postgresql** implementation also thanks to "Vincent Verschuren".

However, it certainly should be a simple process to add any other implementation.  One of the "pros" of `Shuttle.Esb` is that it can easily be extended.

As stated above you can register an implementation of [ISubscriptionManager](https://github.com/Shuttle/Shuttle.Esb/blob/master/Shuttle.Esb/ISubscriptionManager.cs) before calling the `ServiceBus.Register(registry);` method (or use the bootstrapping).

It is a rather simple interface but please let me know if you need some guidance on any of the bits.

**Comment by WoozChucky** [comment]
Thanks a lot for your help, managed to crate a very basic in memory implementation!

Closing this now 👍
