### ISSUE TITLE
Remove superfluous methods from `ISubscriptionManager` interface

### ISSUE THREAD

**Issue by eben-roux** [Shuttle/Shuttle.Esb#38]
Change to:

    public interface ISubscriptionManager
    {
        void Subscribe(string messageTypeFullName);
        IEnumerable<string> GetSubscribedUris(object message);
    }

The following should be extension methods:

        void Subscribe(IEnumerable<string> messageTypeFullNames);
        void Subscribe(IEnumerable<Type> messageTypes);
        void Subscribe(Type messageType);
        void Subscribe<T>();

**Comment by zgabi** [comment]
Agree, in our code they are just throwing NotSupportedExceptions:)

Why do you need to keep the `void Subscribe(string messageTypeFullName);` method? 
It is not called internally from Shuttle, so I think it can be removed, too.

**Comment by eben-roux** [comment]
Interesting point.  But how would a subscriber subscribe then?  All the subscriptions would need to be dealt with out-of-band.

How would you go about designing something like that?  Perhaps another interface.

If the `Subscribe` method is removed then `ISubscriptionManager` could really be `ISubscriptionProvider`.  Come to think of it perhaps a better original name may have been `ISubscriptionRepository` but I got the `SubscriptionManager` idea from NServiceBus since I was using *that* when I started Shuttle.Esb.

**Comment by zgabi** [comment]
In our code the ESB knows the type of the SubscriptionManager, since it was instancieted by it.

And we have a method which accepts a custom SubscriptionData parameter, like:
```
        public void Subscribe(SubscriptionData subscription)
        {
            // adds it to a collection
        }
```

The `GetSubscribedUris` checks this collection.

So it is not type based, you can subscribe a message which has the same type than the other, which won't be published.

E.g the ESB sends the given `MyEntityEvent` message when there is a corresponting `MyEntitySubscriptionData` in its collection:
```
    public class MyEntityEvent : EventMessage
    {
        public Guid StreamId { get; set; };
    }

    public class MyEntitySubscriptionData : SubscriptionData
    {
        public Guid StreamId { get; set; };
    }
```

**Comment by eben-roux** [comment]
I've given this some thought and I suspect that you are absolutely correct! :)

The concrete implementation can provide any registration/subscription mechanisms required.

**Comment by eben-roux** [comment]
https://github.com/Shuttle/Shuttle.Esb/releases/tag/v10.1.0
