### ISSUE TITLE
Shuttle.Core.System dependency is missing from packages.nuspec

### ISSUE THREAD

**Issue by zgabi** [Shuttle/Shuttle.Esb#48]
After upgrading to Esb 10.1.7 we received an Assembly loading exception, which can't find the assembly Shuttle.Core.System.

It is a new reference in v10.1.7, but the dependent nuget package was not installed automatically. (Because it is not sepcified as a dependency)

**Comment by eben-roux** [comment]
Thanks for letting me know.  I have added the dependency to v10.1.8.

Please let me know if that does the trick.  If so I'll unlist the 10.1.7 package from nuget.

**Comment by zgabi** [comment]
Yes, now everything works as expected.
Thanks you for the quick fix.
Merry Christmas!

**Comment by eben-roux** [comment]
Thanks Gábor and a merry Christmas and happy new year to you also :)
