### ISSUE TITLE
Repository contains 2 files with the same name (except the casing)

### ISSUE THREAD

**Issue by zgabi** [Shuttle/Shuttle.Esb#50]
In this folder: https://github.com/Shuttle/Shuttle.Esb/tree/master/Shuttle.Esb/Exceptions
there are 2 ESBConfigurationException.cs files: 

![image](https://user-images.githubusercontent.com/3104253/87694587-a8d47200-c78e-11ea-98b7-661c51a09ba4.png)

When I try to clone the repository I receive the following warning:
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Shuttle.Esb/Exceptions/ESBConfigurationException.cs'
  'Shuttle.Esb/Exceptions/EsbConfigurationException.cs'

**Comment by eben-roux** [comment]
I have deleted `ESBConfigurationException.cs`.  Could you please check whether it is now ok?

**Comment by zgabi** [comment]
Yes, it is ok now. Thanks.
