### ISSUE TITLE
How to create public queues

### ISSUE THREAD

**Issue by MercedeX** [Shuttle/Shuttle.Esb#8]
I'm trying to build the sample. It runs fine on local machine. However when I try to run the client from other machine, it simple fails on Create().Start().

I believe this is because the message queue is created as private hence they are not accessible from outside the machine i.e. from some other machine.

How can I instruct Shuttle-ESB to create a public queue instead of a private one?

**Comment by eben-roux** [comment]
Your message should be a plain DTO and, as such, requires a parameterless constructor:

> System.InvalidOperationException: Channel.Common.Messages.TextMessage cannot be serialized because it does not have a parameterless constructor.

Please let me know if you need any more information.

**Comment by eben-roux** [comment]
Oh, it seems as though the issue has been updated :)

What queuing mechanism are you using?  With Msmq you should be fine sending to private queues (on the same network).  However, your should only read locally from the endpoint.  So the endpoint should have an inbox on the local machine.

**Comment by eben-roux** [comment]
Hi, do you still need some help on this?

**Comment by eben-roux** [comment]
I'm closing this issue for now.
